const data = [
  {
    id:           1,
    img:          "img/Chaveiros/Gato1.jpeg",
    img2:         "img/Chaveiros/Gato2.jpeg",
    nameItem:     "Luna",
    description:  "Chaveiro em forma do gatinho Luna ('Sailor Moon')",
    value:        25.00,
    addCart:      "Adicionar ao carrinho",
    tag:          ["Chaveiros"],
  },
  {
    id:           2,
    img:          "img/Chaveiros/NoFace1.jpeg",
    img2:         "img/Chaveiros/NoFace2.jpeg",
    nameItem:     "No Face",
    description:  "Chaveiro em forma do No Face ('Spirited Away')",
    value:        25.00,
    addCart:      "Adicionar ao carrinho",
    tag:          ["Chaveiros"],
  },
  {
    id:           3,
    img:          "img/Chaveiros/Sapo1.jpeg",
    img2:         "img/Chaveiros/Sapo2.jpeg",
    nameItem:     "Sapinho Festeiro",
    description:  "Chaveiro em forma de sapinho com chapéuzinho de festa",
    value:        25.00,
    addCart:      "Adicionar ao carrinho",
    tag:          ["Chaveiros"],
  },
  {
    id:           4,
    img:          "img/Caixas/CaixaN1.jpeg",
    img2:         "img/Caixas/CaixaN2.jpeg",
    nameItem:     "Cxa Natal",
    description:  "Caixa festiva em comemoração ao Natal",
    value:        50.00,
    addCart:      "Adicionar ao carrinho",
    tag:          ["Caixas"],
  },
  {
    id:           5,
    img:          "img/Caixas/CaixaP1.jpeg",
    img2:         "img/Caixas/CaixaP2.jpeg",
    nameItem:     "Cxa Pokemon Água",
    description:  "Caixa decorada com alguns dos pokemons aquáticos",
    value:        180.00,
    addCart:      "Adicionar ao carrinho",
    tag:          ["Caixas"],
  },
  {
    id:           6,
    img:          "img/Esculturas/Bichos1.jpeg",
    img2:         "img/Esculturas/Bichos2.jpeg",
    nameItem:     "Bichinhos Fazendinha",
    description:  "Conjunto de esculturas em formato de vaquinha, ovelhinha e porquinho",
    value:        60.00,
    addCart:      "Adicionar ao carrinho",
    tag:          ["Esculturas"],
  },
];
